from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('dpr-view/', views.dpr_view, name='dpr_view'),
    path('customer-po-product-details/', views.customer_po_product_details, name='customer_po_product_details'),
    path('supplier-po-product-details/', views.supplier_po_product_details, name='supplier_po_product_details'),
    path('rework-tracking/', views.rework_tracking, name='rework_tracking'),
    path('material-status/', views.material_status, name='material_status'),
    path('accounts-details/', views.accounts_details, name='accounts_details'),
    path('supplier-accounts-details/', views.supplier_accounts_details, name='supplier_accounts_details'),
    path('customer-product/<int:product_id>/payment-status/', views.customer_product_payment_update, name='customer_product_payment_update'),
    path('customer-product/<int:product_id>/followup-update/', views.customer_product_followup_update, name='customer_product_followup_update'),
    path('supplier-product/<int:supplier_product_id>/payment-status/', views.supplier_product_payment_update, name='supplier_product_payment_update'),
    path('supplier-product/<int:supplier_product_id>/followup-update/', views.supplier_product_followup_update, name='supplier_product_followup_update'),
    path('send-supplier-invoice-email/', views.send_supplier_invoice_email, name='send_supplier_invoice_email'),
    path('rfq/', views.rfq_details, name='rfq_details'),
    path('rfq/<int:rfq_id>/email-thread/', views.get_rfq_email_thread, name='get_rfq_email_thread'),
    path('rfq/<int:rfq_id>/send-reply/', views.send_rfq_email_reply, name='send_rfq_email_reply'),
    path('rfq/<int:rfq_id>/sync-inbox/', views.sync_rfq_email_inbox, name='sync_rfq_email_inbox'),
    path('rfq/<int:rfq_id>/quotation/download/', views.rfq_quotation_download, name='rfq_quotation_download'),
    path('dpr/<int:dpr_id>/products/', views.dpr_products, name='dpr_products'),
    path('dpr/<int:dpr_id>/documents/download/', views.dpr_documents_download, name='dpr_documents_download'),
    path('dpr/<int:dpr_id>/generate-po/', views.generate_supplier_po, name='generate_supplier_po'),
    path('dpr/<int:dpr_id>/send-po-email/', views.send_supplier_po_email, name='send_supplier_po_email'),
    path('dpr/<int:dpr_id>/supplier-email-thread/', views.get_supplier_email_thread, name='get_supplier_email_thread'),
    path('dpr/<int:dpr_id>/send-supplier-reply/', views.send_supplier_email_reply, name='send_supplier_email_reply'),
    path('customer-product/<int:product_id>/status/', views.customer_product_status_update, name='customer_product_status_update'),
    path('customer-product/<int:product_id>/invoice/', views.generate_customer_invoice, name='generate_customer_invoice'),
    path('customer-product/<int:product_id>/invoice/<int:invoice_id>/', views.generate_customer_invoice, name='generate_customer_invoice_pdf'),
    path('customer-product/<int:product_id>/address-printout/', views.print_customer_address_pdf, name='print_customer_address_pdf'),
    path('customer-product/<int:product_id>/address-attachment/', views.upload_customer_address_attachment, name='upload_customer_address_attachment'),
    path('customer-product/<int:product_id>/invoice-modal-data/', views.customer_invoice_modal_data, name='customer_invoice_modal_data'),
    path('customer-product/<int:product_id>/supplier-status/', views.supplier_status_details, name='supplier_status_details'),
    path('supplier-product/<int:supplier_product_id>/status/', views.supplier_product_status_update, name='supplier_product_status_update'),
    path('supplier-product/<int:supplier_product_id>/expected-date/', views.supplier_product_expected_date_update, name='supplier_product_expected_date_update'),
    path('dpr/<int:dpr_id>/check-po-date/', views.check_po_date_status, name='check_po_date_status'),
    path('dpr/<int:dpr_id>/save-po-confirmation/', views.save_po_confirmation_date, name='save_po_confirmation_date'),
    path('dpr/<int:dpr_id>/edit/', views.customer_order_edit, name='customer_order_edit'),
    path('dpr/<int:dpr_id>/supplier/', views.dpr_supplier, name='dpr_supplier'),
    path('dpr/<int:dpr_id>/status/', views.dpr_status_update, name='dpr_status_update'),

    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),

    path('customer-order/', views.customer_order, name='customer_order'),
    path('customer-details/', views.customer_details, name='customer_details'),
    path('supplier-details/', views.supplier_details, name='supplier_details'),
    path('add-customer/',views.add_customer,name='add_customer'
),
    path('add-supplier/', views.add_supplier, name='add_supplier'),
    path('add-quotation-ajax/', views.add_quotation_ajax, name='add_quotation_ajax'),
    path('get-customer-quotations/', views.get_customer_quotations, name='get_customer_quotations'),
    path('check-customer-po-number/', views.check_customer_po_number, name='check_customer_po_number'),
    path('send-invoice-email/', views.send_invoice_email, name='send_invoice_email'),
    path('sync-all-mail/', views.sync_all_mail, name='sync_all_mail'),
]

