# Generated by Django 6.0.6 on 2026-07-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN'),
        ),
    ]
