# Generated by Django 5.2.17 on 2026-08-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Terms'),
        ),
    ]
