# Generated by Django 5.2.17 on 2026-08-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='state_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State Code'),
        ),
    ]
