# Generated by Django 5.2.17 on 2026-08-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_supplier_is_sez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
