# Generated by Django 5.2.17 on 2026-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='user_mail_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='User Mail ID'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='User Number'),
        ),
    ]
