# Generated by Django 5.2.17 on 2026-09-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user_mail_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='User Mail ID'),
        ),
    ]
