# Generated by Django 5.2.17 on 2026-09-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_supplier_user_mail_id_supplier_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=255, verbose_name='Supplier Company Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contact Number'),
        ),
    ]
