# Generated by Django 5.2.17 on 2026-08-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_classifier', '0002_emailrecord_imap_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='imap_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
