# Generated by Django 5.2.17 on 2026-08-17 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_classifier', '0003_alter_emailrecord_imap_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
