# Generated by Django 5.2.17 on 2026-08-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_classifier', '0005_alter_emailrecord_ai_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='is_added_to_rfq',
            field=models.BooleanField(default=False, help_text='Indicates if enquiry email has been added to RFQ system'),
        ),
    ]
