# Generated by Django 5.2.17 on 2026-08-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_classifier', '0006_emailrecord_is_added_to_rfq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='ai_category',
            field=models.CharField(choices=[('CUSTOMER_ORDER', 'Customer Order'), ('QUOTATION_REQUEST', 'Quotation Request'), ('PAYMENT_INVOICE', 'Payment / Invoice'), ('SUPPORT_COMPLAINT', 'Support / Complaint'), ('OTHERS', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='final_category',
            field=models.CharField(blank=True, choices=[('CUSTOMER_ORDER', 'Customer Order'), ('QUOTATION_REQUEST', 'Quotation Request'), ('PAYMENT_INVOICE', 'Payment / Invoice'), ('SUPPORT_COMPLAINT', 'Support / Complaint'), ('OTHERS', 'Others')], max_length=30),
        ),
    ]
