# Generated by Django 5.2.17 on 2026-08-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_classifier', '0010_emailrecord_is_added_to_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='ai_category',
            field=models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('CUSTOMER_ORDER', 'Purchase Order'), ('QUOTATION_REQUEST', 'Quotation Request'), ('PAYMENT_INVOICE', 'Payment / Invoice'), ('DISPATCH', 'Dispatch'), ('SUPPORT_COMPLAINT', 'Support / Complaint'), ('OTHERS', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='final_category',
            field=models.CharField(blank=True, choices=[('ENQUIRY', 'Enquiry'), ('CUSTOMER_ORDER', 'Purchase Order'), ('QUOTATION_REQUEST', 'Quotation Request'), ('PAYMENT_INVOICE', 'Payment / Invoice'), ('DISPATCH', 'Dispatch'), ('SUPPORT_COMPLAINT', 'Support / Complaint'), ('OTHERS', 'Others')], max_length=30),
        ),
    ]
