# Generated by Django 5.2.17 on 2026-08-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_classifier', '0011_alter_emailrecord_ai_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='attachment_names',
            field=models.TextField(blank=True, help_text='List of attached filenames', null=True),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='has_attachments',
            field=models.BooleanField(default=False, help_text='Indicates if email has file attachments'),
        ),
    ]
