# Generated by Django 5.2.10 on 2026-05-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('quotation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quotation_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quotation_attachment', models.FileField(blank=True, null=True, upload_to='quotation_files/')),
                ('confirmation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('po_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('po_validity', models.DateField(blank=True, null=True)),
                ('po_attachment', models.FileField(blank=True, null=True, upload_to='po_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
