# Generated by Django 5.2.14 on 2026-05-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpr',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
