# Generated by Django 5.2.14 on 2026-05-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0002_dpr_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpr',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
