# Generated by Django 5.2.10 on 2026-05-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0003_dpr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpr',
            name='total_product',
            field=models.IntegerField(default=0),
        ),
    ]
