# Generated by hand to rename total_product to cust_qty_ordered and add new qty fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0004_dpr_total_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dpr',
            old_name='total_product',
            new_name='cust_qty_ordered',
        ),
        migrations.AddField(
            model_name='dpr',
            name='supplier_qty_ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dpr',
            name='customer_qty_delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dpr',
            name='supplier_qty_received',
            field=models.IntegerField(default=0),
        ),
    ]
