# Generated by Django 5.2.10 on 2026-06-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0006_remove_dpr_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpr',
            name='po_confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
