# Generated by Django 5.2.17 on 2026-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SALES', 'SALES'), ('PURCHASE', 'PURCHASE'), ('ACCOUNTS', 'ACCOUNTS')], default='ADMIN', max_length=20),
        ),
    ]
