# Generated by Django 5.2.17 on 2026-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='User Name')),
                ('user_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Number')),
                ('user_mail_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Mail ID')),
                ('user_designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Designation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
                'ordering': ['user_name'],
            },
        ),
    ]
