# Generated by Django 6.0.6 on 2026-07-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Terms'),
        ),
    ]
