# Generated by Django 6.0.6 on 2026-07-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State Code'),
        ),
    ]
