# Generated by Django 5.2.17 on 2026-08-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_sez',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3, verbose_name='SEZ'),
        ),
    ]
