# Generated by Django 5.2.17 on 2026-09-25 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userdetail'),
        ('customers', '0009_customer_contact_number_customer_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.userdetail', verbose_name='User Detail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='User Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Name'),
        ),
    ]
