# Generated by Django 5.2.17 on 2026-09-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_user_mail_id_customer_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Contact Number'),
        ),
    ]
