# Generated by Django 6.0.6 on 2026-07-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0006_rfqproduct_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='customer_confirmed',
            field=models.BooleanField(default=False, help_text='True when customer confirms the quotation'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='email_sent_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when quotation email was sent to customer', null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='quotation_due_date',
            field=models.DateField(blank=True, help_text='Deadline for customer to confirm quotation (email_sent_date + 3 days)', null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='quotation_email_sent',
            field=models.BooleanField(default=False, help_text='True when quotation email has been successfully sent'),
        ),
    ]
