# Generated by Django 6.0.6 on 2026-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0007_rfq_customer_confirmed_rfq_email_sent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='customer_confirmed',
            field=models.BooleanField(default=False, help_text='Indicates if customer has confirmed the quotation'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='quotation_email_sent',
            field=models.BooleanField(default=False, help_text='Indicates if quotation email has been sent to customer'),
        ),
    ]
