# Generated by Codex on 2026-07-03

from django.db import migrations, models


def copy_rfq_sent_status_to_products(apps, schema_editor):
    RFQProduct = apps.get_model('rfq', 'RFQProduct')
    RFQProduct.objects.filter(
        rfq__quotation_email_sent=True
    ).update(quotation_email_sent=True)


def reset_product_sent_status(apps, schema_editor):
    RFQProduct = apps.get_model('rfq', 'RFQProduct')
    RFQProduct.objects.update(quotation_email_sent=False)


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0008_alter_rfq_customer_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqproduct',
            name='quotation_email_sent',
            field=models.BooleanField(
                default=False,
                help_text='Indicates if quotation email has been sent for this product'
            ),
        ),
        migrations.RunPython(
            copy_rfq_sent_status_to_products,
            reset_product_sent_status,
        ),
    ]
