# Generated by Codex on 2026-07-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0009_rfqproduct_quotation_email_sent'),
        ('suppliers', '0002_supplier_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQSupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='rfq.rfqproduct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_supplier_prices', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['supplier__supplier_name'],
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
