# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0010_rfqsupplierprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqsupplierprice',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
