# Generated by Django 5.2.14 on 2026-07-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0011_rfqsupplierprice_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='quotation_prepared',
            field=models.BooleanField(default=False, help_text='Indicates if quotation has been prepared/generated'),
        ),
        migrations.AddField(
            model_name='rfqproduct',
            name='quotation_prepared',
            field=models.BooleanField(default=False, help_text='Indicates if quotation has been prepared for this product'),
        ),
    ]
