# Generated by Django 6.0.6 on 2026-07-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0013_rfqquotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqproduct',
            name='unit',
            field=models.CharField(blank=True, default="No's", max_length=20, null=True),
        ),
    ]
