# Generated by Django 6.0.6 on 2026-07-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0014_rfqproduct_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rfqquotation',
            unique_together={('rfq', 'quotation_number')},
        ),
    ]
