# Generated by Django 6.0.6 on 2026-07-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0015_alter_rfqquotation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rfqquotation',
            unique_together={('rfq', 'revision_number')},
        ),
    ]
