# Generated by Django 5.2.10 on 2026-08-07 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0017_alter_rfqquotation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=255, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('sender', models.CharField(max_length=255)),
                ('recipients', models.TextField()),
                ('cc_recipients', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('OUT', 'Outgoing'), ('IN', 'Incoming')], default='OUT', max_length=10)),
                ('sent_at', models.DateTimeField()),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_names', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='rfq.rfq')),
            ],
            options={
                'ordering': ['sent_at', 'created_at'],
            },
        ),
    ]
