# Generated by Django 5.2.10 on 2026-08-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0018_rfqemailmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqproduct',
            name='product_type',
            field=models.CharField(blank=True, choices=[('APG', 'APG'), ('ARG', 'ARG'), ('Multi-Gauge', 'Multi-Gauge'), ('unit Std Air', 'unit Std Air'), ('unit SPC Air', 'unit SPC Air'), ('unit Std lvdt', 'unit Std lvdt'), ('unit SPC lvdt', 'unit SPC lvdt'), ('AMC', 'AMC'), ('Service', 'Service'), ('Spares', 'Spares'), ('TPG', 'TPG'), ('TRG', 'TRG'), ('STPG', 'STPG'), ('STRG', 'STRG'), ('PPG', 'PPG'), ('PRG', 'PRG'), ('SPPG', 'SPPG'), ('SPRG', 'SPRG')], max_length=50, null=True),
        ),
    ]
