# Generated by Django 5.2.10 on 2026-08-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_classifier', '0012_emailrecord_attachment_names_and_more'),
        ('rfq', '0020_rfqproduct_product_specifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='source_email',
            field=models.ForeignKey(blank=True, help_text='Original email record from which this RFQ was created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='email_classifier.emailrecord'),
        ),
    ]
