# Generated by Django 5.2.10 on 2026-08-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0021_rfq_source_email'),
        ('suppliers', '0007_alter_supplier_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDatasheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, choices=[('APG', 'APG'), ('ARG', 'ARG'), ('Multi-Gauge', 'Multi-Gauge'), ('unit Std Air', 'unit Std Air'), ('unit SPC Air', 'unit SPC Air'), ('unit Std lvdt', 'unit Std lvdt'), ('unit SPC lvdt', 'unit SPC lvdt'), ('AMC', 'AMC'), ('Service', 'Service'), ('Spares', 'Spares'), ('TPG', 'TPG'), ('TRG', 'TRG'), ('PPG', 'PPG'), ('PRG', 'PRG')], max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasheets', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['supplier__supplier_name', 'product_type', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetPriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Air Plug Gauge', help_text='E.g. Air Plug Gauge, Setting Ring, Central Jet Air Ring Gauge, etc.', max_length=150)),
                ('min_diameter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_diameter', models.DecimalField(blank=True, decimal_places=2, help_text="Null means 'and above'", max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_price_on_request', models.BooleanField(default=False)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='rfq.supplierdatasheet')),
            ],
            options={
                'ordering': ['min_diameter', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_name', models.CharField(help_text='E.g. 3 Jet, Super Blind Bore, Bench Mount', max_length=150)),
                ('spec_key', models.CharField(help_text="Specification key name e.g. 'No. of jets', 'Type of ID', 'Gauge Type'", max_length=100)),
                ('spec_value_match', models.CharField(help_text="Substring or exact match value e.g. '3', 'Super blind', 'Bench mount'", max_length=150)),
                ('adjustment_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FIXED', 'Fixed Amount (₹)')], default='PERCENTAGE', max_length=20)),
                ('adjustment_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='rfq.supplierdatasheet')),
            ],
            options={
                'ordering': ['modifier_name'],
            },
        ),
        migrations.CreateModel(
            name='DatasheetAccessoryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('size_range_label', models.CharField(blank=True, help_text='E.g. 2.0mm to 50.0mm', max_length=150, null=True)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='rfq.supplierdatasheet')),
            ],
            options={
                'ordering': ['product_code', 'item_name'],
            },
        ),
    ]
