# Generated by Django 5.2.10 on 2026-08-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0022_supplierdatasheet_datasheetpricerange_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasheetaccessoryrate',
            options={'ordering': ['item_name']},
        ),
        migrations.AlterModelOptions(
            name='datasheetmodifier',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='datasheetaccessoryrate',
            name='size_range_label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetmodifier',
            name='modifier_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetpricerange',
            name='category_name',
            field=models.CharField(blank=True, default='Base Rate', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='supplierdatasheet',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
