# Generated by Django 5.2.10 on 2026-08-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0023_alter_datasheetaccessoryrate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheetpricerange',
            name='is_price_on_request',
        ),
    ]
