# Generated by Django 5.2.10 on 2026-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0024_remove_datasheetpricerange_is_price_on_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasheetaccessoryrate',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='datasheetaccessoryrate',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
