# Generated by Django 5.2.10 on 2026-08-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0025_alter_datasheetaccessoryrate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetpricerange',
            name='setting_ring_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Setting Ring Rate', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetpricerange',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Air Plug Gauge Rate', max_digits=12),
        ),
    ]
