# Generated by Django 5.2.10 on 2026-08-31 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0027_datasheetextensionrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasheetDepthCollarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_size', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('to_size', models.DecimalField(blank=True, decimal_places=2, help_text="Null means 'and above'", max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Depth Collar Add-on Rate (₹)', max_digits=12)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depth_collars', to='rfq.supplierdatasheet')),
            ],
            options={
                'ordering': ['from_size', 'id'],
            },
        ),
    ]
