# Generated by Django 5.2.10 on 2026-08-31 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0028_datasheetdepthcollarrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasheetAddonRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(help_text='e.g. Right angle attachment, Air jet', max_length=150)),
                ('spec_value', models.CharField(blank=True, help_text="Extra parameter e.g. number of air jets '3'", max_length=150, null=True)),
                ('adjustment_type', models.CharField(choices=[('FIXED', 'Rate (₹)'), ('PERCENTAGE', 'Percentage (%)')], default='FIXED', max_length=20)),
                ('adjustment_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('datasheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='rfq.supplierdatasheet')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
