# Generated by Django 5.2.10 on 2026-05-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpr', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity_ordered', models.IntegerField(default=0)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpr.dpr')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('po_validity', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('po_number', models.CharField(max_length=100)),
                ('po_attachment', models.FileField(blank=True, null=True, upload_to='supplier_po/')),
                ('customer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customerproduct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
    ]
