# Generated by Django 5.2.14 on 2026-05-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='product_attachments/'),
        ),
    ]
