# Generated by Django 5.2.10 on 2026-05-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customerproduct_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default=None, max_length=20, null=True),
        ),
    ]
