# Generated by Django 5.2.10 on 2026-05-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_customerproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='quantity_delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('cancelled', 'Cancelled')], default=None, max_length=20, null=True),
        ),
    ]
