# Generated by Django 5.2.10 on 2026-05-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_customerproduct_quantity_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='quantity_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('partially_delivered', 'Partially Delivered'), ('cancelled', 'Cancelled')], default=None, max_length=20, null=True),
        ),
    ]
