# Generated by Django 5.2.10 on 2026-05-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_supplierproduct_quantity_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
