# Generated by Django 5.2.10 on 2026-05-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_supplierproduct_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='invoice_dc_attachment',
            field=models.FileField(blank=True, null=True, upload_to='invoice_dc_attachments/'),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='invoice_dc_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
