# Generated by Django 5.2.10 on 2026-05-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_customerproduct_invoice_dc_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='product_type',
            field=models.CharField(blank=True, choices=[('APG steel', 'APG steel'), ('ARG steel', 'ARG steel'), ('APG carbide', 'APG carbide'), ('ARG carbide', 'ARG carbide'), ('SAPG', 'SAPG'), ('SARG', 'SARG'), ('Multi-Gauge', 'Multi-Gauge'), ('unit Std Air', 'unit Std Air'), ('unit SPC Air', 'unit SPC Air'), ('unit Std lvdt', 'unit Std lvdt'), ('unit SPC lvdt', 'unit SPC lvdt'), ('AMC', 'AMC'), ('Service', 'Service'), ('Spares', 'Spares'), ('TPG', 'TPG'), ('TRG', 'TRG'), ('STPG', 'STPG'), ('STRG', 'STRG'), ('PPG', 'PPG'), ('PRG', 'PRG'), ('SPPG', 'SPPG'), ('SPRG', 'SPRG')], max_length=50, null=True),
        ),
    ]
