# Generated by Django 5.2.14 on 2026-06-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_customerproduct_delivery_detail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('invoice_pending', 'Invoice Pending'), ('partially_delivered', 'Partially Delivered'), ('cancelled', 'Cancelled')], default=None, max_length=20, null=True),
        ),
    ]
