# Generated by Django 6.0.6 on 2026-07-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_customerproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='mes_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
