# Generated by Django 6.0.6 on 2026-07-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_customerproduct_mes_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='mes_rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customerproduct',
            name='mes_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
