# Generated by Django 6.0.6 on 2026-08-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_supplierproduct_po_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='payment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='payment_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='payment_status',
            field=models.CharField(choices=[('not_received', 'Not Received'), ('partially_received', 'Partially Received'), ('amount_received', 'Amount Received')], default='not_received', max_length=25),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
