# Generated by Django 6.0.6 on 2026-08-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_customerproduct_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='expected_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='follow_up_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
