# Generated by Django 6.0.6 on 2026-08-07 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_customerproduct_expected_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='products.customerproduct')),
            ],
        ),
    ]
