# Generated by Django 5.2.17 on 2026-08-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_customerinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='expected_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='follow_up_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='invoice_dc_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='payment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='payment_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='payment_status',
            field=models.CharField(choices=[('not_received', 'Not Received'), ('partially_received', 'Partially Received'), ('amount_received', 'Amount Received')], default='not_received', max_length=25),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
