# Generated by Django 5.2.17 on 2026-08-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_supplierproduct_expected_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='bill_attachment',
            field=models.FileField(blank=True, null=True, upload_to='supplier_bills/'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier_bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
