# Generated by Django 5.2.17 on 2026-08-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_supplierproduct_bill_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='po_pdf_generated',
            field=models.BooleanField(default=False),
        ),
    ]
