# Generated by Django 5.2.17 on 2026-08-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_add_po_pdf_generated_to_supplierproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproduct',
            name='address_attachment',
            field=models.FileField(blank=True, null=True, upload_to='address_attachments/'),
        ),
    ]
