# Generated by Django 5.2.10 on 2026-08-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_customerproduct_address_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='rework_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
