# Generated by Django 5.2.17 on 2026-09-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_customerproduct_product_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='product_type',
            field=models.CharField(blank=True, choices=[('APG', 'APG'), ('ARG', 'ARG'), ('Carbide Air Caliper', 'Carbide Air Caliper'), ('Carbide APG', 'Carbide APG'), ('Carbide ARG', 'Carbide ARG'), ('Master Setting Rings', 'Master Setting Rings'), ('Multi-Gauge', 'Multi-Gauge'), ('unit Std Air', 'unit Std Air'), ('unit SPC Air', 'unit SPC Air'), ('unit Std lvdt', 'unit Std lvdt'), ('unit SPC lvdt', 'unit SPC lvdt'), ('AMC', 'AMC'), ('Service', 'Service'), ('Spares', 'Spares'), ('TPG', 'TPG'), ('TRG', 'TRG'), ('PPG', 'PPG'), ('PRG', 'PRG')], max_length=50, null=True),
        ),
    ]
