# Generated by Django 5.2.10 on 2026-09-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_customerproduct_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('hsn_code', models.CharField(default='90173029', max_length=20)),
                ('default_delivery_weeks', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTypeSpecField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(max_length=100)),
                ('field_key', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('select', 'Dropdown Select'), ('number', 'Number Input'), ('textarea', 'Textarea / Notes'), ('boolean', 'Yes / No Choice')], default='text', max_length=20)),
                ('select_options', models.TextField(blank=True, help_text='Comma-separated options for dropdown, e.g. Steel, Carbide, D2', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=150, null=True)),
                ('depends_on_field', models.CharField(blank=True, help_text='Field key this depends on', max_length=100, null=True)),
                ('depends_on_value', models.CharField(blank=True, help_text='Value that triggers visibility', max_length=100, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_fields', to='products.producttype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
