# Generated for DPR System to populate Product Types and Spec Fields
from django.db import migrations

PRODUCT_TYPES = [   {   'category': 'Gauge',
        'code': 'APG',
        'default_delivery_weeks': 3,
        'hsn_code': '90173029',
        'id': 1,
        'is_active': True,
        'name': 'Air Plug Gauge'},
    {   'category': 'Gauge',
        'code': 'ARG',
        'default_delivery_weeks': 3,
        'hsn_code': '90173029',
        'id': 2,
        'is_active': True,
        'name': 'Air Ring Gauge'},
    {   'category': 'Gauge',
        'code': 'TPG',
        'default_delivery_weeks': 2,
        'hsn_code': '90173021',
        'id': 3,
        'is_active': True,
        'name': 'Thread Plug Gauge'},
    {   'category': 'Gauge',
        'code': 'TRG',
        'default_delivery_weeks': 2,
        'hsn_code': '90173022',
        'id': 4,
        'is_active': True,
        'name': 'Thread Ring Gauge'},
    {   'category': 'Gauge',
        'code': 'PPG',
        'default_delivery_weeks': 2,
        'hsn_code': '90173021',
        'id': 5,
        'is_active': True,
        'name': 'Plain Plug Gauge'},
    {   'category': 'Gauge',
        'code': 'PRG',
        'default_delivery_weeks': 2,
        'hsn_code': '90173022',
        'id': 6,
        'is_active': True,
        'name': 'Plain Ring Gauge'},
    {   'category': 'Gauge',
        'code': 'Wear Check Plug',
        'default_delivery_weeks': 2,
        'hsn_code': '90173021',
        'id': 7,
        'is_active': True,
        'name': 'Wear Check Plug'},
    {   'category': 'Gauge',
        'code': 'Wear Check Ring',
        'default_delivery_weeks': 2,
        'hsn_code': '90173022',
        'id': 8,
        'is_active': True,
        'name': 'Wear Check Ring'},
    {   'category': 'Unit',
        'code': 'unit Std Air',
        'default_delivery_weeks': 3,
        'hsn_code': '90173029',
        'id': 9,
        'is_active': True,
        'name': 'unit Std Air'},
    {   'category': 'Unit',
        'code': 'unit SPC Air',
        'default_delivery_weeks': 3,
        'hsn_code': '90173029',
        'id': 10,
        'is_active': True,
        'name': 'unit SPC Air'},
    {   'category': 'Unit',
        'code': 'unit Std lvdt',
        'default_delivery_weeks': 3,
        'hsn_code': '90318000',
        'id': 11,
        'is_active': True,
        'name': 'unit Std lvdt'},
    {   'category': 'Unit',
        'code': 'unit SPC lvdt',
        'default_delivery_weeks': 3,
        'hsn_code': '90318000',
        'id': 12,
        'is_active': True,
        'name': 'unit SPC lvdt'},
    {   'category': 'Gauge',
        'code': 'Carbide Air Caliper',
        'default_delivery_weeks': 4,
        'hsn_code': '90173029',
        'id': 13,
        'is_active': True,
        'name': 'Carbide Air Caliper'},
    {   'category': 'Gauge',
        'code': 'Carbide APG',
        'default_delivery_weeks': 4,
        'hsn_code': '90173029',
        'id': 14,
        'is_active': True,
        'name': 'Carbide APG'},
    {   'category': 'Gauge',
        'code': 'Carbide ARG',
        'default_delivery_weeks': 4,
        'hsn_code': '90173029',
        'id': 15,
        'is_active': True,
        'name': 'Carbide ARG'},
    {   'category': 'Gauge',
        'code': 'Master Setting Rings',
        'default_delivery_weeks': 3,
        'hsn_code': '90173023',
        'id': 16,
        'is_active': True,
        'name': 'Master Setting Rings'},
    {   'category': 'Gauge',
        'code': 'Multi-Gauge',
        'default_delivery_weeks': 3,
        'hsn_code': '90318000',
        'id': 17,
        'is_active': True,
        'name': 'Multi-Gauge'},
    {   'category': 'Service',
        'code': 'AMC',
        'default_delivery_weeks': 1,
        'hsn_code': '998719',
        'id': 18,
        'is_active': True,
        'name': 'AMC'},
    {   'category': 'Service',
        'code': 'Service',
        'default_delivery_weeks': 1,
        'hsn_code': '998349',
        'id': 19,
        'is_active': True,
        'name': 'Service'},
    {   'category': 'Spares',
        'code': 'Spares',
        'default_delivery_weeks': 2,
        'hsn_code': '90179000',
        'id': 20,
        'is_active': True,
        'name': 'Spares'}]

SPEC_FIELDS = [   {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 1,
        'is_required': True,
        'placeholder': 'e.g. 10.00 mm',
        'product_type_id': 1,
        'select_options': None,
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 2,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 1,
        'select_options': 'Steel, Carbide, D2',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Measuring load',
        'field_label': 'Measuring Load',
        'field_type': 'text',
        'id': 3,
        'is_required': True,
        'placeholder': 'e.g. Standard',
        'product_type_id': 1,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Type of ID',
        'field_label': 'Type of ID',
        'field_type': 'select',
        'id': 4,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 1,
        'select_options': 'Blind, Through',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Depth collar',
        'field_label': 'Depth Collar',
        'field_type': 'select',
        'id': 5,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 1,
        'select_options': 'Yes, No',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Extension',
        'field_label': 'Extension',
        'field_type': 'text',
        'id': 6,
        'is_required': True,
        'placeholder': 'e.g. 50 mm',
        'product_type_id': 1,
        'select_options': '',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Jet from face',
        'field_label': 'Jet from Face',
        'field_type': 'text',
        'id': 7,
        'is_required': True,
        'placeholder': 'e.g. 3 mm',
        'product_type_id': 1,
        'select_options': '',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'No. of jets',
        'field_label': 'No. of Jets',
        'field_type': 'text',
        'id': 8,
        'is_required': True,
        'placeholder': 'e.g. 2',
        'product_type_id': 1,
        'select_options': '',
        'sort_order': 8},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 9,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 1,
        'select_options': '1A, 2A, 1.5 mm, 1 mm',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Gauge Type',
        'field_label': 'Gauge Type',
        'field_type': 'select',
        'id': 10,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 1,
        'select_options': 'Hand held, Unit mount, Bench mount',
        'sort_order': 10},
    {   'depends_on_field': 'Gauge Type',
        'depends_on_value': 'Bench mount',
        'field_key': 'Bench mount details',
        'field_label': 'Bench Mount Details',
        'field_type': 'text',
        'id': 11,
        'is_required': True,
        'placeholder': 'Enter Bench Mount details',
        'product_type_id': 1,
        'select_options': '',
        'sort_order': 11},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Pull / Chopper',
        'field_label': 'Pull / Chopper',
        'field_type': 'select',
        'id': 12,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 1,
        'select_options': 'Yes, No',
        'sort_order': 12},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 13,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 1,
        'select_options': '',
        'sort_order': 13},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Packaging',
        'field_label': 'Packaging (MABC)',
        'field_type': 'select',
        'id': 14,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 1,
        'select_options': 'MABC: Required, MABC: Not required',
        'sort_order': 14},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 15,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 1,
        'select_options': '',
        'sort_order': 15},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 16,
        'is_required': True,
        'placeholder': 'e.g. 10.00 mm',
        'product_type_id': 2,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 17,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 2,
        'select_options': 'Steel, Carbide, D2',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Measuring load',
        'field_label': 'Measuring Load',
        'field_type': 'text',
        'id': 18,
        'is_required': True,
        'placeholder': 'e.g. Standard',
        'product_type_id': 2,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Type of OD',
        'field_label': 'Type of OD',
        'field_type': 'select',
        'id': 19,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 2,
        'select_options': 'Plain, Stepper',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Jet from face',
        'field_label': 'Jet from Face',
        'field_type': 'text',
        'id': 20,
        'is_required': True,
        'placeholder': 'e.g. 3 mm',
        'product_type_id': 2,
        'select_options': '',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'No. of jets',
        'field_label': 'No. of Jets',
        'field_type': 'text',
        'id': 21,
        'is_required': True,
        'placeholder': 'e.g. 2',
        'product_type_id': 2,
        'select_options': '',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 22,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 2,
        'select_options': '1A, 2A, 1.5 mm, 1 mm',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Gauge Type',
        'field_label': 'Gauge Type',
        'field_type': 'select',
        'id': 23,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 2,
        'select_options': 'Hand held, Unit mount, Bench mount',
        'sort_order': 8},
    {   'depends_on_field': 'Gauge Type',
        'depends_on_value': 'Bench mount',
        'field_key': 'Bench mount details',
        'field_label': 'Bench Mount Details',
        'field_type': 'text',
        'id': 24,
        'is_required': True,
        'placeholder': 'Enter Bench Mount details',
        'product_type_id': 2,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Pull / Chopper',
        'field_label': 'Pull / Chopper',
        'field_type': 'select',
        'id': 25,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 2,
        'select_options': 'Yes, No',
        'sort_order': 10},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 26,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 2,
        'select_options': '',
        'sort_order': 11},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Packaging',
        'field_label': 'Packaging (MABC)',
        'field_type': 'select',
        'id': 27,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 2,
        'select_options': 'MABC: Required, MABC: Not required',
        'sort_order': 12},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 28,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 2,
        'select_options': '',
        'sort_order': 13},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Product Name',
        'field_label': 'Product Name',
        'field_type': 'text',
        'id': 29,
        'is_required': True,
        'placeholder': 'e.g. Air Electronic Unit',
        'product_type_id': 18,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Display',
        'field_label': 'Display',
        'field_type': 'text',
        'id': 30,
        'is_required': True,
        'placeholder': 'e.g. Digital LCD Display',
        'product_type_id': 18,
        'select_options': '',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Features & Accessories',
        'field_label': 'Features & Accessories',
        'field_type': 'textarea',
        'id': 31,
        'is_required': True,
        'placeholder': 'Standard accessories',
        'product_type_id': 18,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Unit Principle',
        'field_label': 'Unit Principle',
        'field_type': 'select',
        'id': 32,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 18,
        'select_options': 'Differential, Piezo-electric, LVDT',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 33,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 18,
        'select_options': '1A, 2A, Single Channel, Dual Channel',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Least Count',
        'field_label': 'Least Count',
        'field_type': 'select',
        'id': 34,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 18,
        'select_options': '0.001 mm, 0.0005 mm, 0.0001 mm',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Additional Features',
        'field_label': 'Additional Features',
        'field_type': 'textarea',
        'id': 35,
        'is_required': False,
        'placeholder': 'Extra custom features',
        'product_type_id': 18,
        'select_options': '',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 36,
        'is_required': True,
        'placeholder': 'e.g. Tag Number',
        'product_type_id': 18,
        'select_options': '',
        'sort_order': 8},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 37,
        'is_required': True,
        'placeholder': 'Remarks',
        'product_type_id': 18,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 38,
        'is_required': True,
        'placeholder': 'e.g. 10.00 mm',
        'product_type_id': 13,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 39,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 13,
        'select_options': 'Steel, Carbide, D2',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Measuring load',
        'field_label': 'Measuring Load',
        'field_type': 'text',
        'id': 40,
        'is_required': True,
        'placeholder': 'e.g. Standard',
        'product_type_id': 13,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Type of OD',
        'field_label': 'Type of OD',
        'field_type': 'select',
        'id': 41,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 13,
        'select_options': 'Plain, Stepper',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Jet from face',
        'field_label': 'Jet from Face',
        'field_type': 'text',
        'id': 42,
        'is_required': True,
        'placeholder': 'e.g. 3 mm',
        'product_type_id': 13,
        'select_options': '',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'No. of jets',
        'field_label': 'No. of Jets',
        'field_type': 'text',
        'id': 43,
        'is_required': True,
        'placeholder': 'e.g. 2',
        'product_type_id': 13,
        'select_options': '',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 44,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 13,
        'select_options': '1A, 2A, 1.5 mm, 1 mm',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Gauge Type',
        'field_label': 'Gauge Type',
        'field_type': 'select',
        'id': 45,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 13,
        'select_options': 'Hand held, Unit mount, Bench mount',
        'sort_order': 8},
    {   'depends_on_field': 'Gauge Type',
        'depends_on_value': 'Bench mount',
        'field_key': 'Bench mount details',
        'field_label': 'Bench Mount Details',
        'field_type': 'text',
        'id': 46,
        'is_required': True,
        'placeholder': 'Enter Bench Mount details',
        'product_type_id': 13,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Pull / Chopper',
        'field_label': 'Pull / Chopper',
        'field_type': 'select',
        'id': 47,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 13,
        'select_options': 'Yes, No',
        'sort_order': 10},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 48,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 13,
        'select_options': '',
        'sort_order': 11},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Packaging',
        'field_label': 'Packaging (MABC)',
        'field_type': 'select',
        'id': 49,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 13,
        'select_options': 'MABC: Required, MABC: Not required',
        'sort_order': 12},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 50,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 13,
        'select_options': '',
        'sort_order': 13},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 51,
        'is_required': True,
        'placeholder': 'e.g. 10.00 mm',
        'product_type_id': 14,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 52,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 14,
        'select_options': 'Steel, Carbide, D2',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Measuring load',
        'field_label': 'Measuring Load',
        'field_type': 'text',
        'id': 53,
        'is_required': True,
        'placeholder': 'e.g. Standard',
        'product_type_id': 14,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Type of ID',
        'field_label': 'Type of ID',
        'field_type': 'select',
        'id': 54,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 14,
        'select_options': 'Blind, Through',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Depth collar',
        'field_label': 'Depth Collar',
        'field_type': 'select',
        'id': 55,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 14,
        'select_options': 'Yes, No',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Extension',
        'field_label': 'Extension',
        'field_type': 'text',
        'id': 56,
        'is_required': True,
        'placeholder': 'e.g. 50 mm',
        'product_type_id': 14,
        'select_options': '',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Jet from face',
        'field_label': 'Jet from Face',
        'field_type': 'text',
        'id': 57,
        'is_required': True,
        'placeholder': 'e.g. 3 mm',
        'product_type_id': 14,
        'select_options': '',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'No. of jets',
        'field_label': 'No. of Jets',
        'field_type': 'text',
        'id': 58,
        'is_required': True,
        'placeholder': 'e.g. 2',
        'product_type_id': 14,
        'select_options': '',
        'sort_order': 8},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 59,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 14,
        'select_options': '1A, 2A, 1.5 mm, 1 mm',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Gauge Type',
        'field_label': 'Gauge Type',
        'field_type': 'select',
        'id': 60,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 14,
        'select_options': 'Hand held, Unit mount, Bench mount',
        'sort_order': 10},
    {   'depends_on_field': 'Gauge Type',
        'depends_on_value': 'Bench mount',
        'field_key': 'Bench mount details',
        'field_label': 'Bench Mount Details',
        'field_type': 'text',
        'id': 61,
        'is_required': True,
        'placeholder': 'Enter Bench Mount details',
        'product_type_id': 14,
        'select_options': '',
        'sort_order': 11},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Pull / Chopper',
        'field_label': 'Pull / Chopper',
        'field_type': 'select',
        'id': 62,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 14,
        'select_options': 'Yes, No',
        'sort_order': 12},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 63,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 14,
        'select_options': '',
        'sort_order': 13},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Packaging',
        'field_label': 'Packaging (MABC)',
        'field_type': 'select',
        'id': 64,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 14,
        'select_options': 'MABC: Required, MABC: Not required',
        'sort_order': 14},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 65,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 14,
        'select_options': '',
        'sort_order': 15},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 66,
        'is_required': True,
        'placeholder': 'e.g. 10.00 mm',
        'product_type_id': 15,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 67,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 15,
        'select_options': 'Steel, Carbide, D2',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Measuring load',
        'field_label': 'Measuring Load',
        'field_type': 'text',
        'id': 68,
        'is_required': True,
        'placeholder': 'e.g. Standard',
        'product_type_id': 15,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Type of OD',
        'field_label': 'Type of OD',
        'field_type': 'select',
        'id': 69,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 15,
        'select_options': 'Plain, Stepper',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Jet from face',
        'field_label': 'Jet from Face',
        'field_type': 'text',
        'id': 70,
        'is_required': True,
        'placeholder': 'e.g. 3 mm',
        'product_type_id': 15,
        'select_options': '',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'No. of jets',
        'field_label': 'No. of Jets',
        'field_type': 'text',
        'id': 71,
        'is_required': True,
        'placeholder': 'e.g. 2',
        'product_type_id': 15,
        'select_options': '',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 72,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 15,
        'select_options': '1A, 2A, 1.5 mm, 1 mm',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Gauge Type',
        'field_label': 'Gauge Type',
        'field_type': 'select',
        'id': 73,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 15,
        'select_options': 'Hand held, Unit mount, Bench mount',
        'sort_order': 8},
    {   'depends_on_field': 'Gauge Type',
        'depends_on_value': 'Bench mount',
        'field_key': 'Bench mount details',
        'field_label': 'Bench Mount Details',
        'field_type': 'text',
        'id': 74,
        'is_required': True,
        'placeholder': 'Enter Bench Mount details',
        'product_type_id': 15,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Pull / Chopper',
        'field_label': 'Pull / Chopper',
        'field_type': 'select',
        'id': 75,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 15,
        'select_options': 'Yes, No',
        'sort_order': 10},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 76,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 15,
        'select_options': '',
        'sort_order': 11},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Packaging',
        'field_label': 'Packaging (MABC)',
        'field_type': 'select',
        'id': 77,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 15,
        'select_options': 'MABC: Required, MABC: Not required',
        'sort_order': 12},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 78,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 15,
        'select_options': '',
        'sort_order': 13},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 79,
        'is_required': True,
        'placeholder': 'e.g. 10.00 mm',
        'product_type_id': 16,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 80,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 16,
        'select_options': 'Steel, Carbide, D2',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Measuring load',
        'field_label': 'Measuring Load',
        'field_type': 'text',
        'id': 81,
        'is_required': True,
        'placeholder': 'e.g. Standard',
        'product_type_id': 16,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Type of OD',
        'field_label': 'Type of OD',
        'field_type': 'select',
        'id': 82,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 16,
        'select_options': 'Plain, Stepper',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Jet from face',
        'field_label': 'Jet from Face',
        'field_type': 'text',
        'id': 83,
        'is_required': True,
        'placeholder': 'e.g. 3 mm',
        'product_type_id': 16,
        'select_options': '',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'No. of jets',
        'field_label': 'No. of Jets',
        'field_type': 'text',
        'id': 84,
        'is_required': True,
        'placeholder': 'e.g. 2',
        'product_type_id': 16,
        'select_options': '',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 85,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 16,
        'select_options': '1A, 2A, 1.5 mm, 1 mm',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Gauge Type',
        'field_label': 'Gauge Type',
        'field_type': 'select',
        'id': 86,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 16,
        'select_options': 'Hand held, Unit mount, Bench mount',
        'sort_order': 8},
    {   'depends_on_field': 'Gauge Type',
        'depends_on_value': 'Bench mount',
        'field_key': 'Bench mount details',
        'field_label': 'Bench Mount Details',
        'field_type': 'text',
        'id': 87,
        'is_required': True,
        'placeholder': 'Enter Bench Mount details',
        'product_type_id': 16,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Pull / Chopper',
        'field_label': 'Pull / Chopper',
        'field_type': 'select',
        'id': 88,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 16,
        'select_options': 'Yes, No',
        'sort_order': 10},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 89,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 16,
        'select_options': '',
        'sort_order': 11},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Packaging',
        'field_label': 'Packaging (MABC)',
        'field_type': 'select',
        'id': 90,
        'is_required': False,
        'placeholder': '',
        'product_type_id': 16,
        'select_options': 'MABC: Required, MABC: Not required',
        'sort_order': 12},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 91,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 16,
        'select_options': '',
        'sort_order': 13},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Product Name',
        'field_label': 'Product Name',
        'field_type': 'text',
        'id': 92,
        'is_required': True,
        'placeholder': 'e.g. Air Electronic Unit',
        'product_type_id': 17,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Display',
        'field_label': 'Display',
        'field_type': 'text',
        'id': 93,
        'is_required': True,
        'placeholder': 'e.g. Digital LCD Display',
        'product_type_id': 17,
        'select_options': '',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Features & Accessories',
        'field_label': 'Features & Accessories',
        'field_type': 'textarea',
        'id': 94,
        'is_required': True,
        'placeholder': 'Standard accessories',
        'product_type_id': 17,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Unit Principle',
        'field_label': 'Unit Principle',
        'field_type': 'select',
        'id': 95,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 17,
        'select_options': 'Differential, Piezo-electric, LVDT',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 96,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 17,
        'select_options': '1A, 2A, Single Channel, Dual Channel',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Least Count',
        'field_label': 'Least Count',
        'field_type': 'select',
        'id': 97,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 17,
        'select_options': '0.001 mm, 0.0005 mm, 0.0001 mm',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Additional Features',
        'field_label': 'Additional Features',
        'field_type': 'textarea',
        'id': 98,
        'is_required': False,
        'placeholder': 'Extra custom features',
        'product_type_id': 17,
        'select_options': '',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 99,
        'is_required': True,
        'placeholder': 'e.g. Tag Number',
        'product_type_id': 17,
        'select_options': '',
        'sort_order': 8},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 100,
        'is_required': True,
        'placeholder': 'Remarks',
        'product_type_id': 17,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 101,
        'is_required': True,
        'placeholder': 'e.g. M10 x 1.5 - 6H',
        'product_type_id': 5,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 102,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 5,
        'select_options': 'Steel, Carbide, OHNS',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 103,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 5,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 104,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 5,
        'select_options': '',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 105,
        'is_required': True,
        'placeholder': 'e.g. M10 x 1.5 - 6H',
        'product_type_id': 6,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 106,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 6,
        'select_options': 'Steel, Carbide, OHNS',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 107,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 6,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 108,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 6,
        'select_options': '',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Product Name',
        'field_label': 'Product Name',
        'field_type': 'text',
        'id': 109,
        'is_required': True,
        'placeholder': 'e.g. Air Electronic Unit',
        'product_type_id': 19,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Display',
        'field_label': 'Display',
        'field_type': 'text',
        'id': 110,
        'is_required': True,
        'placeholder': 'e.g. Digital LCD Display',
        'product_type_id': 19,
        'select_options': '',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Features & Accessories',
        'field_label': 'Features & Accessories',
        'field_type': 'textarea',
        'id': 111,
        'is_required': True,
        'placeholder': 'Standard accessories',
        'product_type_id': 19,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Unit Principle',
        'field_label': 'Unit Principle',
        'field_type': 'select',
        'id': 112,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 19,
        'select_options': 'Differential, Piezo-electric, LVDT',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 113,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 19,
        'select_options': '1A, 2A, Single Channel, Dual Channel',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Least Count',
        'field_label': 'Least Count',
        'field_type': 'select',
        'id': 114,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 19,
        'select_options': '0.001 mm, 0.0005 mm, 0.0001 mm',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Additional Features',
        'field_label': 'Additional Features',
        'field_type': 'textarea',
        'id': 115,
        'is_required': False,
        'placeholder': 'Extra custom features',
        'product_type_id': 19,
        'select_options': '',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 116,
        'is_required': True,
        'placeholder': 'e.g. Tag Number',
        'product_type_id': 19,
        'select_options': '',
        'sort_order': 8},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 117,
        'is_required': True,
        'placeholder': 'Remarks',
        'product_type_id': 19,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Product Name',
        'field_label': 'Product Name',
        'field_type': 'text',
        'id': 118,
        'is_required': True,
        'placeholder': 'e.g. Air Electronic Unit',
        'product_type_id': 20,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Display',
        'field_label': 'Display',
        'field_type': 'text',
        'id': 119,
        'is_required': True,
        'placeholder': 'e.g. Digital LCD Display',
        'product_type_id': 20,
        'select_options': '',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Features & Accessories',
        'field_label': 'Features & Accessories',
        'field_type': 'textarea',
        'id': 120,
        'is_required': True,
        'placeholder': 'Standard accessories',
        'product_type_id': 20,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Unit Principle',
        'field_label': 'Unit Principle',
        'field_type': 'select',
        'id': 121,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 20,
        'select_options': 'Differential, Piezo-electric, LVDT',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 122,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 20,
        'select_options': '1A, 2A, Single Channel, Dual Channel',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Least Count',
        'field_label': 'Least Count',
        'field_type': 'select',
        'id': 123,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 20,
        'select_options': '0.001 mm, 0.0005 mm, 0.0001 mm',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Additional Features',
        'field_label': 'Additional Features',
        'field_type': 'textarea',
        'id': 124,
        'is_required': False,
        'placeholder': 'Extra custom features',
        'product_type_id': 20,
        'select_options': '',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 125,
        'is_required': True,
        'placeholder': 'e.g. Tag Number',
        'product_type_id': 20,
        'select_options': '',
        'sort_order': 8},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 126,
        'is_required': True,
        'placeholder': 'Remarks',
        'product_type_id': 20,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 127,
        'is_required': True,
        'placeholder': 'e.g. M10 x 1.5 - 6H',
        'product_type_id': 3,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 128,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 3,
        'select_options': 'Steel, Carbide, OHNS',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 129,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 3,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 130,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 3,
        'select_options': '',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 131,
        'is_required': True,
        'placeholder': 'e.g. M10 x 1.5 - 6H',
        'product_type_id': 4,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 132,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 4,
        'select_options': 'Steel, Carbide, OHNS',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 133,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 4,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 134,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 4,
        'select_options': '',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Product Name',
        'field_label': 'Product Name',
        'field_type': 'text',
        'id': 135,
        'is_required': True,
        'placeholder': 'e.g. Air Electronic Unit',
        'product_type_id': 10,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Display',
        'field_label': 'Display',
        'field_type': 'text',
        'id': 136,
        'is_required': True,
        'placeholder': 'e.g. Digital LCD Display',
        'product_type_id': 10,
        'select_options': '',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Features & Accessories',
        'field_label': 'Features & Accessories',
        'field_type': 'textarea',
        'id': 137,
        'is_required': True,
        'placeholder': 'Standard accessories',
        'product_type_id': 10,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Unit Principle',
        'field_label': 'Unit Principle',
        'field_type': 'select',
        'id': 138,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 10,
        'select_options': 'Differential, Piezo-electric, LVDT',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 139,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 10,
        'select_options': '1A, 2A, Single Channel, Dual Channel',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Least Count',
        'field_label': 'Least Count',
        'field_type': 'select',
        'id': 140,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 10,
        'select_options': '0.001 mm, 0.0005 mm, 0.0001 mm',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Additional Features',
        'field_label': 'Additional Features',
        'field_type': 'textarea',
        'id': 141,
        'is_required': False,
        'placeholder': 'Extra custom features',
        'product_type_id': 10,
        'select_options': '',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 142,
        'is_required': True,
        'placeholder': 'e.g. Tag Number',
        'product_type_id': 10,
        'select_options': '',
        'sort_order': 8},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 143,
        'is_required': True,
        'placeholder': 'Remarks',
        'product_type_id': 10,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Product Name',
        'field_label': 'Product Name',
        'field_type': 'text',
        'id': 144,
        'is_required': True,
        'placeholder': 'e.g. Air Electronic Unit',
        'product_type_id': 12,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Display',
        'field_label': 'Display',
        'field_type': 'text',
        'id': 145,
        'is_required': True,
        'placeholder': 'e.g. Digital LCD Display',
        'product_type_id': 12,
        'select_options': '',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Features & Accessories',
        'field_label': 'Features & Accessories',
        'field_type': 'textarea',
        'id': 146,
        'is_required': True,
        'placeholder': 'Standard accessories',
        'product_type_id': 12,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Unit Principle',
        'field_label': 'Unit Principle',
        'field_type': 'select',
        'id': 147,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 12,
        'select_options': 'Differential, Piezo-electric, LVDT',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 148,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 12,
        'select_options': '1A, 2A, Single Channel, Dual Channel',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Least Count',
        'field_label': 'Least Count',
        'field_type': 'select',
        'id': 149,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 12,
        'select_options': '0.001 mm, 0.0005 mm, 0.0001 mm',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Additional Features',
        'field_label': 'Additional Features',
        'field_type': 'textarea',
        'id': 150,
        'is_required': False,
        'placeholder': 'Extra custom features',
        'product_type_id': 12,
        'select_options': '',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 151,
        'is_required': True,
        'placeholder': 'e.g. Tag Number',
        'product_type_id': 12,
        'select_options': '',
        'sort_order': 8},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 152,
        'is_required': True,
        'placeholder': 'Remarks',
        'product_type_id': 12,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Product Name',
        'field_label': 'Product Name',
        'field_type': 'text',
        'id': 153,
        'is_required': True,
        'placeholder': 'e.g. Air Electronic Unit',
        'product_type_id': 9,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Display',
        'field_label': 'Display',
        'field_type': 'text',
        'id': 154,
        'is_required': True,
        'placeholder': 'e.g. Digital LCD Display',
        'product_type_id': 9,
        'select_options': '',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Features & Accessories',
        'field_label': 'Features & Accessories',
        'field_type': 'textarea',
        'id': 155,
        'is_required': True,
        'placeholder': 'Standard accessories',
        'product_type_id': 9,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Unit Principle',
        'field_label': 'Unit Principle',
        'field_type': 'select',
        'id': 156,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 9,
        'select_options': 'Differential, Piezo-electric, LVDT',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 157,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 9,
        'select_options': '1A, 2A, Single Channel, Dual Channel',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Least Count',
        'field_label': 'Least Count',
        'field_type': 'select',
        'id': 158,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 9,
        'select_options': '0.001 mm, 0.0005 mm, 0.0001 mm',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Additional Features',
        'field_label': 'Additional Features',
        'field_type': 'textarea',
        'id': 159,
        'is_required': False,
        'placeholder': 'Extra custom features',
        'product_type_id': 9,
        'select_options': '',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 160,
        'is_required': True,
        'placeholder': 'e.g. Tag Number',
        'product_type_id': 9,
        'select_options': '',
        'sort_order': 8},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 161,
        'is_required': True,
        'placeholder': 'Remarks',
        'product_type_id': 9,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Product Name',
        'field_label': 'Product Name',
        'field_type': 'text',
        'id': 162,
        'is_required': True,
        'placeholder': 'e.g. Air Electronic Unit',
        'product_type_id': 11,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Display',
        'field_label': 'Display',
        'field_type': 'text',
        'id': 163,
        'is_required': True,
        'placeholder': 'e.g. Digital LCD Display',
        'product_type_id': 11,
        'select_options': '',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Features & Accessories',
        'field_label': 'Features & Accessories',
        'field_type': 'textarea',
        'id': 164,
        'is_required': True,
        'placeholder': 'Standard accessories',
        'product_type_id': 11,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Unit Principle',
        'field_label': 'Unit Principle',
        'field_type': 'select',
        'id': 165,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 11,
        'select_options': 'Differential, Piezo-electric, LVDT',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Module',
        'field_label': 'Module',
        'field_type': 'select',
        'id': 166,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 11,
        'select_options': '1A, 2A, Single Channel, Dual Channel',
        'sort_order': 5},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Least Count',
        'field_label': 'Least Count',
        'field_type': 'select',
        'id': 167,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 11,
        'select_options': '0.001 mm, 0.0005 mm, 0.0001 mm',
        'sort_order': 6},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Additional Features',
        'field_label': 'Additional Features',
        'field_type': 'textarea',
        'id': 168,
        'is_required': False,
        'placeholder': 'Extra custom features',
        'product_type_id': 11,
        'select_options': '',
        'sort_order': 7},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 169,
        'is_required': True,
        'placeholder': 'e.g. Tag Number',
        'product_type_id': 11,
        'select_options': '',
        'sort_order': 8},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 170,
        'is_required': True,
        'placeholder': 'Remarks',
        'product_type_id': 11,
        'select_options': '',
        'sort_order': 9},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 171,
        'is_required': True,
        'placeholder': 'e.g. M10 x 1.5 - 6H',
        'product_type_id': 7,
        'select_options': '',
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 172,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 7,
        'select_options': 'Steel, Carbide, OHNS',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 173,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 7,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 174,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 7,
        'select_options': '',
        'sort_order': 4},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Size',
        'field_label': 'Size',
        'field_type': 'text',
        'id': 175,
        'is_required': True,
        'placeholder': 'e.g. M10 x 1.5 - 6H',
        'product_type_id': 8,
        'select_options': None,
        'sort_order': 1},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Material',
        'field_label': 'Material',
        'field_type': 'select',
        'id': 176,
        'is_required': True,
        'placeholder': '',
        'product_type_id': 8,
        'select_options': 'Steel, Carbide, OHNS',
        'sort_order': 2},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Engraving details',
        'field_label': 'Engraving Details',
        'field_type': 'text',
        'id': 177,
        'is_required': True,
        'placeholder': 'e.g. Marking text',
        'product_type_id': 8,
        'select_options': '',
        'sort_order': 3},
    {   'depends_on_field': None,
        'depends_on_value': None,
        'field_key': 'Remarks',
        'field_label': 'Specification Remarks',
        'field_type': 'textarea',
        'id': 178,
        'is_required': True,
        'placeholder': 'Additional specifications or remarks',
        'product_type_id': 8,
        'select_options': '',
        'sort_order': 4}]

def populate_product_types(apps, schema_editor):
    ProductType = apps.get_model('products', 'ProductType')
    ProductTypeSpecField = apps.get_model('products', 'ProductTypeSpecField')

    pt_map = {}
    for pt in PRODUCT_TYPES:
        obj, _ = ProductType.objects.update_or_create(
            id=pt['id'],
            defaults={
                'name': pt['name'],
                'code': pt['code'],
                'category': pt['category'],
                'hsn_code': pt['hsn_code'],
                'default_delivery_weeks': pt['default_delivery_weeks'],
                'is_active': pt['is_active'],
            }
        )
        pt_map[pt['id']] = obj

    for spec in SPEC_FIELDS:
        pt_obj = pt_map.get(spec['product_type_id']) or ProductType.objects.filter(id=spec['product_type_id']).first()
        if not pt_obj:
            continue
        ProductTypeSpecField.objects.update_or_create(
            id=spec['id'],
            defaults={
                'product_type': pt_obj,
                'field_label': spec['field_label'],
                'field_key': spec['field_key'],
                'field_type': spec['field_type'],
                'select_options': spec['select_options'],
                'is_required': spec['is_required'],
                'placeholder': spec['placeholder'],
                'depends_on_field': spec['depends_on_field'],
                'depends_on_value': spec['depends_on_value'],
                'sort_order': spec['sort_order'],
            }
        )

def unpopulate_product_types(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_producttype_producttypespecfield'),
    ]

    operations = [
        migrations.RunPython(populate_product_types, reverse_code=unpopulate_product_types),
    ]
