# Generated by Django 5.2.17 on 2026-09-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_populate_product_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='product_specifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
